POST http://localhost:3003/user
Content-Type: application/json

{
   "name": "Jana", 
   "email": "Jana@labenu.com" ,
   "password": "heyimjana",
   "role": "ADMIN"
}

#####

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "Jana@labenu.com" ,
   "password": "heyimjana"
}

#####

GET http://localhost:3003/user
Content-Type: application/json

#####

POST http://localhost:3003/recipe
Content-Type: application/json

{
   "title":"Torta de Limão",
   "description":"Deliciosa torta de limão que vai conquistar o crush."
}
